import numpy

BLOCK_SIZE = 15
BLOCK_RADIUS = BLOCK_SIZE / 2
SNAKE_BODY_STRIDE = 10.
SNAKE_BORN_LENGTH = 5
WIDTH = 800
HEIGHT = 600

WIDTH_BLOCK = WIDTH // BLOCK_SIZE
HEIGHT_BLOCK = HEIGHT // BLOCK_SIZE

FPS = 30
GENERATE_COIN_TICK = 0.1 * FPS
NATURAL_COIN_DISAPPEAR = 60  # Unit: Second(s)

DATA_SIZE = 15
DATA_SPREAD = DATA_SIZE // 2
DATA_CENTER = DATA_SIZE // 2 + 1

AVAILABLE_COIN_DISTANCE = numpy.hypot(BLOCK_SIZE * DATA_SIZE / 2, BLOCK_SIZE * DATA_SIZE / 2)
