SNAKE_RADIUS = 8
COIN_RADIUS = 5
SNAKE_BODY_STRIDE = 10.
BLOCK_STRIDE = 10
WIDTH = 500
HEIGHT = 800

WIDTH_BLOCK = WIDTH // BLOCK_STRIDE
HEIGHT_BLOCK = HEIGHT // BLOCK_STRIDE

FPS = 100
GENERATE_COIN_TICK = 2
NATURAL_COIN_DISAPPEAR = 60  # Unit: Second(s)
