SNAKE_RADIUS = 10
COIN_RADIUS = 5
SNAKE_BODY_STRIDE = 5.
BLOCK_STRIDE = 10
WIDTH = 500
HEIGHT = 800

WIDTH_BLOCK = WIDTH // BLOCK_STRIDE
HEIGHT_BLOCK = HEIGHT // BLOCK_STRIDE

FPS = 30
GENERATE_COIN_TICK = FPS * 5
NATURAL_COIN_DISAPPEAR = 60  # Unit: Second(s)
